apiVersion: v1
kind: Pod
metadata:
  name: svc-pod
  labels:
    app: test
spec: 
  containers:
    - name:
      image: jenkins/jenkins 
      ports:
        - containerPort: 80
          protocol: TCP


  

               
